version: '3.1'

services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo_top-api
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express-mongo_top-api
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo_top-api:27017/

  top.api:
    image: docker.pkg.github.com/aachemezov/top-api/top-api:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env